version: "3"

services:
  tcp-server:
    build: ./server
    container_name: tcp-server
    ports:
      - "9000:9000"
    networks:
      - tcp-net

  tcp-client:
    build: ./client
    container_name: tcp-client
    depends_on:
      - tcp-server
    networks:
      - tcp-net

networks:
  tcp-net: